### ISSUE TITLE
Runtime incompatibility

### ISSUE THREAD

**Issue by dasjestyr** [rjperes/Postal.NET#1]
Is it possible to get a build that doesn't depend on System.Runtime 4.0.20.0?

**Comment by rjperes** [comment]
Hi,

Yes, I will do some changes today.
Thanks for your interest!

RP

**Comment by rjperes** [comment]
Actually, I need to think this more carefully. I don't think the way that I am currently building this is right.
Out of curiosity, where are you using this - plain .NET, PCL, .NET Core,...?

**Comment by rjperes** [comment]
The project now targets .NET Core.
