### ISSUE TITLE
How to use this library in asp mvc project?

### ISSUE THREAD

**Issue by MehdiSaeedifar** [rjperes/Postal.NET#2]
Hi,
How to use this library in an asp mvc project?
When i try to integrate this library to a web api project, the subscribe method is called but it will not return back to controller.

**Comment by s30n4** [comment]
use PublishAsync method dude

**Comment by MehdiSaeedifar** [comment]
@s30n4  thanks.

**Comment by rjperes** [comment]
Hi, guys!
Thank you for your interest in Postal.NET! :-)
Do you see any value in this project? Do you actually use it? Anything you would like to see here?
Do let me know! Cheers.

**Comment by MehdiSaeedifar** [comment]
Hi,
We have decided to use Postal.NET for communication between our app modules in a large scale ASP Web API project.

I think the main advantage of Postal.NET is string based channel and topic that very handy in plugin based application.

Any way thanks for your great project.

**Comment by rjperes** [comment]
Hi, Mehdi!
I'm very honored! Do let me know if you face any problems or would like to see something in Postal.NET.
Cheers!
