### ISSUE TITLE
No .netcore support

### ISSUE THREAD

**Issue by s30n4** [rjperes/Postal.NET#3]
Hi
I want to use postal.net for asp.net core project but i get this error:
"The dependency Postal.NET 1.0.0.5 does not support framework .NETCoreApp,Version=v1.0."    after installed them.

**Comment by rjperes** [comment]
Hi! Thank you for your interest!
Yes, it's a common request. I will do my best, in the next days, to give you an answer on this.

**Comment by rjperes** [comment]
Hi,
I will push the Nuget package including support for .NET Core very soon.

**Comment by rjperes** [comment]
Hi,
A new build of Postal.NET is available in Nuget with support for .NET Core as well as .NET "classic".
Please let me know if you face any problems.
