### ISSUE TITLE
.Net core support

### ISSUE THREAD

**Issue by HamedFathi** [rjperes/Postal.NET#4]
Hi
I checked your project you can releade .Net core version easily for main postal.net and other related libraries.

Please update them 
Thank for your awesome libraries

**Comment by rjperes** [comment]
Hi, Hamed! The Nuget package for Postal itself is already working with .NET Core, and I will port the others plus the source code. Thank you for your interest!

**Comment by HamedFathi** [comment]
@rjperes thanks waiting ...

**Comment by rjperes** [comment]
All projects target .NET Standard 2.0 now.
